# The second and third paragraph of each veil's story. The first is design.VEIL_LINES[level].
# gen.py joins them and refuses any veil longer than VEIL_MAX characters, which is what fits in
# the Depth Gauge above the "Part the veil" button.
VEIL_MAX = 330

SHALLOWS = [
    "Shallow gray water, and under it a floor that gives a little when you lean on it, as if it has been waiting to be asked.",
    "It is colder a few fathoms down. It is the cold of a room nobody has been in for a while.",
    "The floor is thinner than it was. I can feel the next place through it, like a draft through a door.",
]

BOTTOM = [
    "There is nothing under this. No floor to give, no next place to feel through it.",
    "The dive goes on anyway, fathom after fathom of the same dark, and brings up what the dream still has.",
    "Whatever happens now happens on the road.",
]

MORE = {
    5: ("The Oneiri will not touch the bitten ones. They carry them to the edge of the Drift and let them go.",
        "I asked what had eaten it. They looked at me for a long time."),
    6: ("The Oneiri slow down here, the way people slow down near a house where someone is sleeping.",
        "Past the slope, the pieces stop drifting and start to settle."),
    7: ("The Oneiri walk it with their heads down, reading the prints.",
        "Some of the prints are mine. I have not been here before."),
    8: ("Shells, buttons, a glove, a door key. Nothing large. Everything someone once kept in a pocket.",
        "The Oneiri sort it into piles I do not understand yet."),
    9: ("They hand me the things they find as if I might know what they are.",
        "Often I do. I do not like how often."),
    10: ("They are not deep. Whoever left them was small, and in no hurry, and always going the same way.",
         "I followed them for a while. They go where I am going."),
    11: ("I have not thought about that marble in thirty years. I kept it on the windowsill, where the light came through it.",
         "I put it in my pocket. The Oneiri watched me do it."),
    12: ("Standing at the edge of it I understood that this whole shore is made of things that fell out of pockets.",
         "Mine, mostly."),
    13: ("I did not stay to look. It looked back for a little longer than I did.",
         "The silt here is wet, and heavier, and it keeps the shape of a hand."),
    14: ("The Oneiri sit with me at the edge, more of them every day.",
         "None of us says anything. It feels like the most useful thing I have done in years."),
    15: ("Even the Oneiri are quieter here. They move as if they are trying not to wake it.",
         "I have started to wonder what it is."),
    16: ("It is warm, the water. Warmer than it should be, like a bath someone has only just left.",
         "They call me back before I am out of my depth, every time."),
    17: ("The Oneiri all turned to look at the same place, and then all looked away from it.",
         "I asked them what was down there. They went back to work."),
    18: ("The quiet here is the quiet of a held breath, of someone standing very still in the next room.",
         "I found I was holding mine too."),
    19: ("Each one is set down carefully, with its wick trimmed, facing out into the dark.",
         "Someone meant to come back and light them. Nobody did."),
    20: ("Something lives at the bottom of the Stillwater, and it has been waiting, and it is not them it is waiting for.",
         "They stayed with me anyway."),
    21: ("I counted forty lamps before I stopped counting. Every one of them is out.",
         "The Oneiri walk between them as if through a graveyard."),
    22: ("Knee height, all of them. The height of a child's hand holding a match.",
         "I keep crouching to reach them, and each time I feel smaller."),
    23: ("The light is small and yellow and only reaches as far as my knees.",
         "It is enough. I had forgotten how much a small light is enough."),
    24: ("They held their hands out to it. One of them laughed, I think. It sounded like a kettle.",
         "We lit six more before we went on."),
    25: ("Facing outward, not in. Whoever set them was not lighting a room. They were keeping something out.",
         "I do not know what. I think I used to."),
    26: ("The dark past the last lamp is thicker, the way dark is thicker at the end of a hallway.",
         "The Oneiri took a lamp with them when we went on."),
    27: ("The Oneiri put their hands to it and hum along.",
         "Whatever is here is old, and cold, and it has been kept very carefully."),
    28: ("The cold holds its shape, as if poured into a mold and left to set.",
         "The Oneiri cut it out in blocks and carry it back to the Palace. It does not melt."),
    29: ("They are quicker with their hands than they were. They have started building things I did not ask for.",
         "A bench. A railing. A shelf, at a child's height."),
    30: ("The blanket on it is folded back, as if someone just got up.",
         "I did not touch it. I did not want to find out whether it was still warm."),
    31: ("I stood at the top of it for a long time. The Oneiri waited with me.",
         "Then one of them took my hand, and we went down."),
    32: ("I have always hated this kind of dark. I never knew why. I thought everyone did.",
         "The Oneiri keep close. Nobody lights a lamp. It seems to matter that we do not."),
    33: ("Fourteen. There were fourteen stairs in the house I grew up in, and I counted them every night.",
         "There are more than fourteen here. I stopped counting at a hundred."),
    34: ("I stopped. It stopped. I went on, and after a while it went on too.",
         "The Oneiri did not hear it, or pretended not to."),
    35: ("I did not tell them to. I think they are carrying the lamps for me.",
         "The lamps help. I wish they did not help so much."),
    36: ("I know the house. I do not want to know the house.",
         "The Oneiri stopped at the bottom stair and would not come any closer."),
    37: ("The paint is the right color. The step still has the crack in it. The light is on upstairs.",
         "I stood on the path for a long time and did not go in."),
    38: ("The curtains are drawn. Through the gap in them there is a small light, the kind you plug into a wall.",
         "I used to fall asleep watching that light."),
    39: ("Around the house the dark goes on forever. Nothing else is lit, anywhere.",
         "I think the house is what the dark is afraid of. Or the other way round."),
    40: ("The door is not locked. It never was. It is open a hand's width, the way I always asked for it to be.",
         "The Oneiri will wait for me outside."),
    41: ("I can feel it in my feet, a slow tug toward the deep.",
         "The Oneiri lean into it the way you lean into a wind."),
    42: ("They have started answering my questions. Not with words. With where they point.",
         "Most of it points down."),
    43: ("I let it take me a little way, just to feel where it wanted me to go.",
         "It knew. It has always known."),
    44: ("Those are the ones the Oneiri swim in. They say it is like remembering being young.",
         "I swam in one. It was."),
    45: ("Everything the pull has carried off is here, sunk and softened, still moving slightly.",
         "I found my bicycle. I left it where it was."),
    46: ("The water tastes like the back of the throat just before crying.",
         "The Oneiri do not drink it. I did, once, and wished I had not."),
    47: ("The sun comes up off it so bright it hurts. Nothing grows. Nothing moves.",
         "I walked out into it until the Palace was a speck behind me."),
    48: ("A hand. A face. A shoe, a child's, with the laces still tied.",
         "The Oneiri walk around them carefully, as if they are graves."),
    49: ("They are tall and white and very still, and they stand the way people stand at a funeral.",
         "They are keeping something. I think it is the grief itself."),
    50: ("I had not cried in years. I did not know I had so much of it.",
         "The Saltwives came a little closer after that. Not close. Closer."),
    51: ("A beach of opened shells, each one holding something small and bright.",
         "The Oneiri gather them in armfuls and will not tell me what they are."),
    52: ("Every pearl was something that hurt and would not stop. The shell grew around it to keep the hurt in.",
         "They are beautiful. That is the worst part."),
    53: ("The small hurts make the largest pearls. The ones you did not think were worth crying over.",
         "The beds go on for miles."),
    54: ("I was twelve. I laughed along. I have never stopped hearing it.",
         "The Tidefolk took the pearl back from me gently, the way you take something sharp from a child."),
    55: ("They do not judge. They polish them, and put them back, and move on to the next.",
         "There are so many of mine."),
    56: ("It is at the very bottom of the bed, older than all the rest, and it has not stopped growing.",
         "The Tidefolk will not touch it."),
    57: ("They lie in a long line on the shore, like shells after a storm, all empty.",
         "I walked the whole length of it and did not find one that had not been eaten."),
    58: ("I looked at the bites for a long time. They are all the same size. A child's mouth.",
         "The Oneiri watched me understand it."),
    59: ("I let it out of me when I was six, and I have been feeding it ever since, every time I looked away.",
         "It is mine. It is mine to end."),
    60: ("It leads down, into places the Oneiri have not been back to in a long time.",
         "They gave me what they had, and I did not ask whether it would be enough."),
    61: ("Hollowed out, every one, and still standing, as if they have not been told yet.",
         "The wind makes a sound in them like someone breathing through their teeth."),
    62: ("I stood still too long. I felt it come up through my shoes.",
         "It is not cold, exactly. It is the feeling of having forgotten something important."),
    63: ("They cannot move. They are still here. They know exactly what ate them.",
         "They lean toward the Palace when the wind blows that way."),
    64: ("It knew what she sounds like. It knew what she would say.",
         "I did not answer. It kept calling for a long time after I had gone."),
    65: ("Hundreds of them, stacked to the dark, all ticking, none of them agreeing.",
         "The sound of them made my chest tight before I knew why."),
    66: ("I stood among them and my heart sped up to match them.",
         "Every one of them is sure something is about to happen."),
    67: ("They are thin and quick and anxious, and they apologize every time they see me.",
         "One of them is winding a clock that is only a face painted on the wall."),
    68: ("It has gained years on me already.",
         "The Clockfolk have been trying to slow it down since before I arrived."),
    69: ("Every late night, every held breath before a phone call, every sure thing that might not be.",
         "It ate all of it. It grew so fat on worry."),
    70: ("I almost stood up. I almost answered.",
         "The Oneiri held my sleeve until the name went on to someone else."),
    71: ("Everyone here is sitting very straight, holding something on their knees, waiting to be called.",
         "No one looks at anyone else."),
    72: ("Somebody offered me a magazine. It was from the year I turned thirty.",
         "I read the whole thing. I do not remember any of it."),
    73: ("I did sit in a room like this once, for a whole night. I did not let go.",
         "I had forgotten that I did not let go."),
    74: ("Everyone keeps watching it anyway. I did too.",
         "When I finally stood up to leave, nobody noticed."),
    75: ("It goes down in the other direction, into the reflection.",
         "The Oneiri would not step onto it. I went first."),
    76: ("Every step I take, a hundred of me take it too, a moment late.",
         "I stopped once. They did not all stop."),
    77: ("It stands where my reflection should stand. It moves when I move.",
         "It is practising."),
    78: ("It was a very good smile. It was mine.",
         "I did not look at the mirrors again for a long time."),
    79: ("It is tired of being the dark under a child's bed. It wants to be the child, grown.",
         "It wants to wake up in the morning as me."),
    80: ("They are all there, every people of the dream, lamps lit.",
         "Nobody asked them to come. I did not know how badly I needed them to."),
    81: ("The Oneiri, the Drifters, the Tidefolk. Others I have only glimpsed until now.",
         "They go quiet when they see me. Then they start to sing."),
    82: ("They set their lamps along the shore, low, at a child's height.",
         "I recognized the spacing. It was mine."),
    83: ("The Saltwives brought walls. The Clockfolk brought time. The Hollowed brought their memory of being eaten.",
         "It is more than I have ever been given."),
    84: ("I used to think I would have to do this alone. I thought that was the point of it.",
         "It was not the point of it."),
    85: ("I have been walking toward this door my whole life.",
         "The peoples followed me down to it, and stopped at the threshold, and waited."),
    86: ("It smelled exactly the same. Wet coats and dust.",
         "I used to hide in here from the dark in the rest of the house. I did not think about what was in here with me."),
    87: ("The coats go on for miles, and behind them more coats, and behind those the dark.",
         "The Oneiri hold hands in a line so none of us gets lost."),
    88: ("It is not hiding any more. It has stopped pretending not to be here.",
         "I can feel it listening to me breathe."),
    89: ("The beam is small and yellow and wobbles in my hand.",
         "It is exactly as brave as I was at eight. It turns out that is quite brave."),
    90: ("It is on a shelf at knee height, among the boots, trimmed and steady.",
         "Nobody has touched it in thirty years. It has not gone out."),
    91: ("The dark leans in toward it and never quite gets close.",
         "I sat by it for a long time, the way I used to sit by the nightlight."),
    92: ("The whole time the Nobody has been growing, this was here, and it was mine too.",
         "The Oneiri sat down around it with me and did not say anything."),
    93: ("The Nobody leans toward it too, the way you lean toward a window in a house you cannot leave.",
         "I almost felt sorry for it."),
    94: ("They bring it things: a bench, a railing, a shelf at a child's height.",
         "It is the most beautiful thing in the dream."),
    95: ("The landing of the house I grew up in, and the hallway, and my door at the end of it.",
         "The lamp's light reaches almost to the door, and then stops."),
    96: ("Every nightmare I ever had is still in me, and every one of them is strong enough to win.",
         "I have not decided. I have not decided."),
    97: ("The hall light is on. My bedroom is dark.",
         "I am standing on the wrong side of the door, and I am grown."),
    98: ("I used to lie in bed and watch that stripe of light, and nothing crossed it, and I slept.",
         "Something is on the other side of it now, holding its breath."),
    99: ("I can hear it breathing in the dark of my room, in when I breathe out.",
         "It sounds like a boy trying not to cry."),
    100: ("I have gone as far down as there is.",
          "Whatever is left to do, I do on the road, with everyone who came with me."),
}
