// What Lies In The Depths — the whole dream, from the first journal entry to the last battle.
//
// GENERATED by Tools/Content/gen.py from Tools/Content/design.py. Edit the design and run
// the generator; a hand edit here is overwritten. No word lives here: every name, blurb,
// paragraph and effect line is read from Strings.json by key, and the effect lines are
// written from the effects themselves, so a card never says what its numbers do not do.
//
// Every number is a first-pass placeholder, tuned only far enough that a simulated player
// walks the whole path (Tools/Content/sim). The five chapters are twenty veils each; the
// last veil of chapters two to four is sunk with a resource only that chapter's golden beat
// brings (Dread, Chorus, Mettle), which is the roadblock. The road has thirty places; the
// last six open only at the bottom, and only once the choice is made.
using System.Collections.Generic;
using UnityEngine;
using Ursine.Economy;
using Ursine.Text;

namespace WhatLiesInTheDepths.Data
{
    public static class OpeningContent
    {
        static List<Amount> C(params object[] kv)
        {
            var list = new List<Amount>();
            for (int i = 0; i + 1 < kv.Length; i += 2)
                list.Add(new Amount((string)kv[i], System.Convert.ToDouble(kv[i + 1])));
            return list;
        }
        static List<string> L(params string[] s) => new List<string>(s);
        static List<Effect> Fx_(params Effect[] e) => new List<Effect>(e);
        static Effect E(Fx kind, string of, double n) => new Effect(kind, of, n);
        static string T(string key) => Loc.T(key);
        static List<string> Lines(string key) => Loc.Lines(key);

        public static void Fill(Dream s)
        {
            Resources(s);
            Rules(s);
            Focus(s);
            Constructs(s);
            Upgrades(s);
            Revelations(s);
            Visions(s);
            Veils(s);
            Road(s);
            Journal(s);
            Achievements(s);
        }

        static void Res_(Dream s, string k, double m, ResGroup g, string glyph, List<string> requires)
        {
            s.resources.Add(new Res { k = k, n = T("res." + k), c = 0, m = m, g = (int)g, glyph = glyph,
                                      hostile = g == ResGroup.AgainstYou, requires = requires });
        }

        static void Resources(Dream s)
        {
            Res_(s, "reverie", 10, ResGroup.Gathered, "reverie", L("done:absorb>=1"));
            Res_(s, "silt", 15, ResGroup.Gathered, "silt", L("fathoms>=1"));
            Res_(s, "moonsilver", 40, ResGroup.Gathered, "moonsilver", L("rev:cold"));
            Res_(s, "ember", 20, ResGroup.Gathered, "ember", L("rev:warmth"));
            Res_(s, "tallow", 30, ResGroup.Gathered, "tallow", L("rev:fat"));
            Res_(s, "salt", 60, ResGroup.Gathered, "salt", L("rev:salt"));
            Res_(s, "nacre", 40, ResGroup.Gathered, "nacre", L("vision:garden"));
            Res_(s, "echo", 10, ResGroup.Yours, "echo", L("done:conjure>=1"));
            Res_(s, "oneiri", 0, ResGroup.Yours, "oneiri", L("owned:hut>=1"));
            Res_(s, "lucidity", 20, ResGroup.Yours, "lucidity", L("rev:quiet"));
            Res_(s, "hush", 30, ResGroup.Yours, "hush", L("rev:darkquiet"));
            Res_(s, "vellum", 40, ResGroup.Yours, "vellum", L("rev:written"));
            Res_(s, "ward", 50, ResGroup.Yours, "ward", L("rev:holds"));
            Res_(s, "chorus", 60, ResGroup.Yours, "chorus", L("rev:mine"));
            Res_(s, "mettle", 60, ResGroup.Yours, "mettle", L("built:forge"));
            Res_(s, "dread", 100, ResGroup.AgainstYou, "dread", L("vision:door"));
            Res_(s, "umbra", 100, ResGroup.AgainstYou, "umbra", L("rev:fear"));
            s.startOnShow["dread"] = 20;
        }

        static void Rules(Dream s)
        {
            s.rules.Add(new Rule { id = "focus-menu", when = L("start"), grants = L("menu:focus") });
            s.rules.Add(new Rule { id = "ledger", when = L("done:absorb>=1"), grants = L("col:ledger") });
            s.rules.Add(new Rule { id = "constructs-menu", when = L("max:reverie"), grants = L("menu:constructs") });
            s.rules.Add(new Rule { id = "revelations-menu", when = L("fathoms>=15"), grants = L("menu:revelations") });
            s.rules.Add(new Rule { id = "revelations-on-full-silt", when = L("max:silt"), grants = L("menu:revelations") });
            s.rules.Add(new Rule { id = "binding", when = L("rev:shown"), grants = L("bind:oneiri") });
            s.rules.Add(new Rule { id = "visions-menu", when = L("rev:camefrom"), grants = L("menu:visions") });
            s.rules.Add(new Rule { id = "assault-menu", when = L("rev:mine"), grants = L("menu:assault") });
            s.rules.Add(new Rule { id = "chose-dark", when = L("rev:fear"), grants = L("chose") });
            s.rules.Add(new Rule { id = "chose-light", when = L("rev:shut"), grants = L("chose") });
        }

        static void Task(Dream s, string id, string section, string g, List<Amount> cost, List<Amount> gain,
                         double seconds, int cap, List<string> requires)
        {
            s.tasks.Add(new FocusTask
            {
                section = T("focus.section." + section), id = id, g = g,
                n = T("focus." + id + ".name"), b = T("focus." + id + ".blurb"),
                cost = cost, gain = gain, baseSeconds = seconds, w = 0, cap = cap, p = 0, seen = true,
                requires = requires
            });
        }

        static void Focus(Dream s)
        {
            Task(s, "absorb", "stillness", "sit", null, C("reverie", 1), 6, 12, L("start"));
            Task(s, "conjure", "stillness", "card", C("reverie", 1), C("echo", 1), 6, 10, L("rev:sifting"));
            Task(s, "still", "stillness", "still", C("echo", 2, "reverie", 2), C("lucidity", 1), 10, 8, L("rev:quiet"));
            Task(s, "draw", "labor", "draw", C("silt", 2), C("moonsilver", 1), 8, 10, L("rev:cold"));
            Task(s, "kindle", "labor", "kindle", C("reverie", 2), C("ember", 1), 8, 8, L("rev:warmth"));
            Task(s, "render", "labor", "render", C("silt", 1, "ember", 1), C("tallow", 2), 10, 8, L("rev:fat"));
            Task(s, "tend", "labor", "tend", C("tallow", 2), C("lucidity", 2), 12, 8, L("rev:lamps"));
            Task(s, "sit", "labor", "sit", null, C("hush", 2, "reverie", 1), 10, 8, L("rev:darkquiet"));
            Task(s, "weep", "listening", "weep", C("hush", 2), C("salt", 2), 10, 10, L("rev:salt"));
            Task(s, "sift", "listening", "sift", C("silt", 2, "salt", 2), C("nacre", 1), 12, 10, L("vision:garden"));
            Task(s, "page", "listening", "page", C("hush", 2, "echo", 3), C("vellum", 1), 14, 10, L("rev:written"));
            Task(s, "watch", "muster", "watch", C("hush", 2, "salt", 2), C("ward", 1), 12, 12, L("rev:stand"));
            Task(s, "rally", "muster", "rally", C("echo", 3), C("chorus", 1), 10, 14, L("rev:mine"));
            Task(s, "temper", "muster", "temper", C("ember", 3, "moonsilver", 4, "chorus", 2), C("mettle", 2), 16, 16, L("built:forge"));
            Task(s, "sing", "many", "sing", C("chorus", 3), C("lucidity", 3, "ward", 1), 12, 16, L("rev:everypeople"));
            Task(s, "dredge", "many", "dredge", C("dread", 5), C("umbra", 2), 10, 16, L("rev:fear"));
            Task(s, "release", "many", "release", C("dread", 5), C("lucidity", 3), 10, 16, L("rev:shut"));
        }

        static ConstructDef Build(Dream s, string g, ConstructKind kind, List<Amount> cost, int housing,
                                  List<Effect> effects, List<string> requires, float x, float y)
        {
            var c = new ConstructDef
            {
                g = g, n = T("construct." + g + ".name"), kind = kind, b = T("construct." + g + ".blurb"),
                fx = Lines("construct." + g + ".fx"), baseCost = cost, cost = cost, growth = 1.15,
                housing = housing, effects = effects, owned = 0, built = false, seen = true,
                palacePos = new Vector2(x, y), requires = requires
            };
            s.constructs.Add(c);
            return c;
        }

        static void Constructs(Dream s)
        {
            ConstructDef c;
            c = Build(s, "altar", ConstructKind.Works, C("reverie", 10), 0, null, L("max:reverie"), 440, 430);
            c.once = true;
            c.landmark = true; c.kindLabel = T("construct.altar.kind"); c.line = T("construct.altar.line");
            c.grants = L("col:gauge");
            c = Build(s, "hut", ConstructKind.Dwellings, C("reverie", 10, "echo", 5), 1, null, L("rev:listening"), 736, 206);
            c = Build(s, "cistern", ConstructKind.Reservoirs, C("silt", 12), 0, Fx_(E(Fx.Cap, "silt", 20), E(Fx.Cap, "reverie", 5), E(Fx.Cap, "echo", 3)), L("rev:room"), 212, 716);
            c.growth = 1.02;
            c = Build(s, "spindle", ConstructKind.Works, C("reverie", 12, "silt", 10), 0, Fx_(E(Fx.Rate, "reverie", 0.2)), L("rev:hums"), 132, 148);
            c = Build(s, "moonwell", ConstructKind.Reservoirs, C("reverie", 20, "silt", 10), 0, Fx_(E(Fx.Cap, "reverie", 25), E(Fx.Rate, "reverie", 0.1), E(Fx.Cap, "lucidity", 3)), L("rev:stillkeeps"), 138, 566);
            c = Build(s, "winch", ConstructKind.Works, C("moonsilver", 15, "silt", 12), 0, Fx_(E(Fx.Rate, "moonsilver", 0.15), E(Fx.Cap, "moonsilver", 20)), L("rev:seam"), 296, 236);
            c = Build(s, "press", ConstructKind.Works, C("silt", 12, "ember", 8), 0, Fx_(E(Fx.Rate, "tallow", 0.15), E(Fx.Cap, "tallow", 15), E(Fx.Cap, "ember", 5)), L("rev:fat"), 286, 96);
            c = Build(s, "lamprow", ConstructKind.Works, C("tallow", 15, "moonsilver", 10), 0, Fx_(E(Fx.DiveCost, null, 0.04), E(Fx.Rate, "tallow", 0.05)), L("rev:lamps"), 118, 330);
            c = Build(s, "longhouse", ConstructKind.Dwellings, C("moonsilver", 40, "salt", 20, "echo", 30), 6, null, L("rev:tidefolk"), 700, 82);
            c = Build(s, "reliquary", ConstructKind.Reservoirs, C("echo", 30, "moonsilver", 20), 0, Fx_(E(Fx.Cap, "echo", 40), E(Fx.Cap, "nacre", 20)), L("rev:somewhere"), 376, 766);
            c = Build(s, "scriptorium", ConstructKind.Works, C("hush", 20, "moonsilver", 25), 0, Fx_(E(Fx.Rate, "vellum", 0.05), E(Fx.Cap, "vellum", 20)), L("rev:written"), 236, 396);
            c = Build(s, "saltpans", ConstructKind.Works, C("silt", 25, "hush", 15), 0, Fx_(E(Fx.Rate, "salt", 0.15), E(Fx.Cap, "salt", 30)), L("rev:letsea"), 56, 244);
            c = Build(s, "nightlight", ConstructKind.Wards, C("tallow", 60, "ember", 30, "moonsilver", 40), 0, Fx_(E(Fx.Rate, "dread", -0.5), E(Fx.Cap, "ward", 10)), L("vision:vigil"), 560, 600);
            c.once = true;
            c = Build(s, "rampart", ConstructKind.Wards, C("moonsilver", 40, "salt", 25), 0, Fx_(E(Fx.Rate, "dread", -0.1), E(Fx.Cap, "ward", 8)), L("rev:holds"), 750, 576);
            c = Build(s, "chorusstone", ConstructKind.Wards, C("echo", 50, "salt", 40), 0, Fx_(E(Fx.Cap, "ward", 12), E(Fx.Cap, "chorus", 20)), L("rev:manyvoices"), 636, 734);
            c = Build(s, "belltower", ConstructKind.Works, C("moonsilver", 60, "chorus", 20), 0, Fx_(E(Fx.Rate, "chorus", 0.1)), L("won:bell"), 404, 76);
            c = Build(s, "forge", ConstructKind.Works, C("moonsilver", 150, "ember", 60, "chorus", 40, "vellum", 30), 0, Fx_(E(Fx.Cap, "mettle", 100)), L("rev:made"), 340, 300);
            c.once = true;
            c = Build(s, "hallmany", ConstructKind.Dwellings, C("moonsilver", 120, "chorus", 60, "salt", 60), 12, Fx_(E(Fx.Speed, "*", 0.03)), L("rev:everypeople"), 560, 250);
            c = Build(s, "hallstrengths", ConstructKind.Works, C("mettle", 20, "vellum", 20), 0, Fx_(E(Fx.Power, "Sworn", 0.05), E(Fx.Cap, "mettle", 15)), L("rev:goodat"), 60, 420);
            c = Build(s, "beacon", ConstructKind.Wards, C("tallow", 200, "ember", 100, "mettle", 40), 0, Fx_(E(Fx.Enemy, null, 0.3)), L("parted>=90"), 800, 700);
            c.once = true;
            c = Build(s, "kiln", ConstructKind.Works, C("mettle", 60, "ember", 60), 0, Fx_(E(Fx.Rate, "umbra", 1), E(Fx.Rate, "dread", 0.3), E(Fx.Exodus, null, 1)), L("rev:fear"), 170, 250);
            c.once = true;
        }

        static void Upgrades(Dream s)
        {
            s.upgrades.Add(new UpgradeDef { id = "abode", target = UpgradeTarget.Construct, of = "hut", when = L("rev:walls"), n = T("upgrade.abode.name"), b = T("upgrade.abode.blurb"), art = "abode", fx = Lines("upgrade.abode.fx"), housing = 3, cost = C("moonsilver", 12, "echo", 10) });
            s.upgrades.Add(new UpgradeDef { id = "whispers", target = UpgradeTarget.Resource, of = "echo", when = L("rev:answers"), n = T("upgrade.whispers.name"), art = "whispers", ceiling = 60 });
            s.upgrades.Add(new UpgradeDef { id = "converse", target = UpgradeTarget.Focus, of = "conjure", when = L("rev:answers"), n = T("upgrade.converse.name"), b = T("upgrade.converse.blurb") });
            s.upgrades.Add(new UpgradeDef { id = "nm-unflinching", target = UpgradeTarget.Unit, of = "unflinching", when = L("rev:fear"), n = T("upgrade.nm-unflinching.name"), b = T("upgrade.nm-unflinching.blurb"), art = "hollowriders", cost = C("mettle", 4, "umbra", 4), powerScale = 2.5 });
            s.upgrades.Add(new UpgradeDef { id = "nm-laughing", target = UpgradeTarget.Unit, of = "laughing", when = L("rev:fear"), n = T("upgrade.nm-laughing.name"), b = T("upgrade.nm-laughing.blurb"), art = "grinning", cost = C("mettle", 8, "umbra", 6), powerScale = 2.5 });
            s.upgrades.Add(new UpgradeDef { id = "nm-plainspoken", target = UpgradeTarget.Unit, of = "plainspoken", when = L("rev:fear"), n = T("upgrade.nm-plainspoken.name"), b = T("upgrade.nm-plainspoken.blurb"), art = "voices", cost = C("mettle", 15, "umbra", 8), powerScale = 2.5 });
            s.upgrades.Add(new UpgradeDef { id = "nm-sentinel", target = UpgradeTarget.Unit, of = "sentinel", when = L("rev:fear"), n = T("upgrade.nm-sentinel.name"), b = T("upgrade.nm-sentinel.blurb"), art = "drowned", cost = C("mettle", 28, "umbra", 12), powerScale = 2.5 });
            s.upgrades.Add(new UpgradeDef { id = "nm-chorus", target = UpgradeTarget.Unit, of = "chorus", when = L("rev:fear"), n = T("upgrade.nm-chorus.name"), b = T("upgrade.nm-chorus.blurb"), art = "wailing", cost = C("mettle", 50, "umbra", 20), powerScale = 2.5 });
            s.upgrades.Add(new UpgradeDef { id = "nm-dreamwright", target = UpgradeTarget.Unit, of = "dreamwright", when = L("rev:fear"), n = T("upgrade.nm-dreamwright.name"), b = T("upgrade.nm-dreamwright.blurb"), art = "stairs", cost = C("mettle", 90, "umbra", 30), powerScale = 2.5 });
        }

        static RevelationDef Rev(Dream s, string k, string g, List<Amount> cost, bool great, float ring, float deg,
                                 List<Effect> effects, List<string> requires)
        {
            var r = new RevelationDef
            {
                k = k, g = g, n = T("rev." + k + ".name"), kind = T("rev." + k + ".kind"),
                bl = T("rev." + k + ".text"), fx = Lines("rev." + k + ".fx"), cost = cost, great = great,
                ring = ring, angle = deg * Mathf.Deg2Rad, effects = effects, requires = requires
            };
            s.revelations.Add(r);
            return r;
        }

        static void Revelations(Dream s)
        {
            RevelationDef r;
            r = Rev(s, "sifting", "key", C("silt", 15), false, 306f, 0.0f, null, L("fathoms>=15"));
            r = Rev(s, "listening", "branch", C("echo", 10), false, 388f, 137.5f, null, L("max:echo"));
            r = Rev(s, "shown", "knot", C("echo", 10, "silt", 10), false, 306f, 275.0f, null, L("owned:hut>=1"));
            r = Rev(s, "room", "glass", C("silt", 15), false, 388f, 52.5f, null, L("max:silt"));
            r = Rev(s, "hums", "spiral", C("reverie", 10, "silt", 15), false, 306f, 190.0f, null, L("parted>=6"));
            r = Rev(s, "down", "stair", C("silt", 25, "echo", 10), false, 388f, 327.5f, Fx_(E(Fx.DiveCost, null, 0.08)), L("parted>=9", "rev:room"));
            r = Rev(s, "quiet", "knot", C("reverie", 20, "echo", 10, "silt", 20), false, 306f, 105.0f, null, L("parted>=13"));
            r = Rev(s, "stillkeeps", "glass", C("lucidity", 15, "silt", 15), false, 388f, 242.5f, null, L("max:lucidity"));
            r = Rev(s, "remember", "branch", C("lucidity", 20, "reverie", 30), false, 306f, 20.0f, Fx_(E(Fx.Gain, "absorb", 1)), L("rev:stillkeeps", "owned:hut>=3"));
            r = Rev(s, "afraid", "mirror", C("lucidity", 20, "echo", 20, "silt", 35), true, 388f, 157.5f, Fx_(E(Fx.Speed, "*", 0.1)), L("parted>=19"));
            r = Rev(s, "cold", "key", C("silt", 35, "lucidity", 15), false, 306f, 295.0f, null, L("parted>=20"));
            r = Rev(s, "walls", "knot", C("moonsilver", 25, "echo", 20), false, 388f, 72.5f, null, L("owned:hut>=5", "rev:cold"));
            r = Rev(s, "warmth", "lantern", C("moonsilver", 15, "reverie", 40), false, 306f, 210.0f, null, L("parted>=23"));
            r = Rev(s, "fat", "scales", C("ember", 20, "silt", 25), false, 388f, 347.5f, null, L("max:ember"));
            r = Rev(s, "lamps", "lantern", C("tallow", 10, "moonsilver", 20), false, 306f, 125.0f, null, L("got:tallow"));
            r = Rev(s, "seam", "stair", C("moonsilver", 40, "lucidity", 20), false, 388f, 262.5f, null, L("parted>=26"));
            r = Rev(s, "drifters", "branch", C("echo", 30, "moonsilver", 30), false, 306f, 40.0f, Fx_(E(Fx.Housing, "hut", 1), E(Fx.Gain, "draw", 0.5)), L("rev:walls", "parted>=28"));
            r = Rev(s, "darkquiet", "glass", C("tallow", 20, "lucidity", 25), false, 388f, 177.5f, null, L("parted>=31"));
            r = Rev(s, "knot", "knot", C("hush", 30, "echo", 30), false, 306f, 315.0f, Fx_(E(Fx.CapPct, "echo", 1), E(Fx.CapPct, "hush", 1), E(Fx.CapPct, "ember", 1)), L("max:hush"));
            r = Rev(s, "tasted", "scales", C("hush", 40, "tallow", 30, "lucidity", 30), false, 388f, 92.5f, Fx_(E(Fx.Gain, "dive", 0.25)), L("parted>=35"));
            r = Rev(s, "camefrom", "mirror", C("lucidity", 40, "hush", 50, "moonsilver", 60), true, 306f, 230.0f, null, L("parted>=37"));
            r = Rev(s, "answers", "branch", C("echo", 40, "lucidity", 30), false, 388f, 7.5f, Fx_(E(Fx.Gain, "conjure", 0.5)), L("parted>=40"));
            r = Rev(s, "salt", "scales", C("hush", 40, "echo", 40), false, 306f, 145.0f, null, L("parted>=46"));
            r = Rev(s, "letsea", "glass", C("salt", 60, "silt", 50), false, 388f, 282.5f, null, L("max:salt"));
            r = Rev(s, "breath", "glass", C("lucidity", 40, "moonsilver", 60), false, 306f, 60.0f, Fx_(E(Fx.DiveSpeed, null, 0.15)), L("parted>=49"));
            r = Rev(s, "tidefolk", "spiral", C("salt", 60, "moonsilver", 60, "echo", 40), false, 388f, 197.5f, null, L("parted>=51"));
            r = Rev(s, "somewhere", "key", C("nacre", 30, "echo", 50), false, 306f, 335.0f, null, L("max:nacre"));
            r = Rev(s, "written", "stair", C("nacre", 20, "hush", 25, "moonsilver", 50), false, 388f, 112.5f, null, L("parted>=54"));
            r = Rev(s, "holds", "knot", C("moonsilver", 50, "salt", 40), false, 306f, 250.0f, null, L("parted>=43"));
            r = Rev(s, "stand", "lantern", C("salt", 30, "hush", 20), false, 388f, 27.5f, null, L("owned:rampart>=1"));
            r = Rev(s, "owed", "scales", C("ward", 20, "lucidity", 40), false, 306f, 165.0f, Fx_(E(Fx.Rate, "dread", -0.3)), L("owned:rampart>=3"));
            r = Rev(s, "grew", "spiral", C("nacre", 40, "vellum", 20), false, 388f, 302.5f, Fx_(E(Fx.VisionCost, null, 0.1)), L("vdone:tide>=3"));
            r = Rev(s, "mine", "mirror", C("vellum", 30, "nacre", 40, "lucidity", 60), true, 306f, 80.0f, null, L("parted>=57", "vision:well"));
            r = Rev(s, "lost", "glass", C("ward", 15, "echo", 40), false, 388f, 217.5f, Fx_(E(Fx.Power, "Levied", 0.2)), L("lost:any"));
            r = Rev(s, "manyvoices", "branch", C("chorus", 20, "salt", 50), false, 306f, 355.0f, Fx_(E(Fx.Gain, "rally", 0.5)), L("parted>=63"));
            r = Rev(s, "nothiding", "key", C("chorus", 20, "vellum", 20), false, 388f, 132.5f, Fx_(E(Fx.Enemy, null, 0.05)), L("won:deepend"));
            r = Rev(s, "clocks", "glass", C("moonsilver", 100, "lucidity", 50), false, 306f, 270.0f, Fx_(E(Fx.Speed, "*", 0.1)), L("parted>=65"));
            r = Rev(s, "worry", "scales", C("ward", 30, "salt", 60), false, 388f, 47.5f, Fx_(E(Fx.Rate, "dread", -0.4)), L("parted>=70"));
            r = Rev(s, "borrowed", "lantern", C("chorus", 30, "ward", 30), false, 306f, 185.0f, Fx_(E(Fx.Power, "Levied", 0.25)), L("won>=6"));
            r = Rev(s, "wants", "mirror", C("vellum", 30, "nacre", 40), false, 388f, 322.5f, null, L("won:mile"));
            r = Rev(s, "made", "spiral", C("chorus", 60, "vellum", 40, "lucidity", 60, "ward", 30), true, 306f, 100.0f, null, L("parted>=77", "vision:tenant"));
            r = Rev(s, "wicks", "lantern", C("tallow", 80, "chorus", 30), false, 388f, 237.5f, Fx_(E(Fx.Gain, "render", 1), E(Fx.Gain, "tend", 1), E(Fx.Gain, "kindle", 1)), L("parted>=80"));
            r = Rev(s, "saltwives", "scales", C("salt", 100, "ward", 40), false, 306f, 15.0f, Fx_(E(Fx.CapPct, "ward", 0.5)), L("won:ninth"));
            r = Rev(s, "clockfolk", "glass", C("moonsilver", 150, "lucidity", 60), false, 388f, 152.5f, Fx_(E(Fx.DiveSpeed, null, 0.5)), L("parted>=83"));
            r = Rev(s, "hollowed", "branch", C("ward", 40, "nacre", 50), false, 306f, 290.0f, Fx_(E(Fx.Enemy, null, 0.1)), L("won:exam"));
            r = Rev(s, "everypeople", "spiral", C("chorus", 80, "lucidity", 80), false, 388f, 67.5f, null, L("rev:wicks", "rev:saltwives", "rev:clockfolk", "rev:hollowed"));
            r = Rev(s, "goodat", "key", C("mettle", 20, "vellum", 30), false, 306f, 205.0f, Fx_(E(Fx.CapPct, "mettle", 1)), L("vision:duck"));
            r = Rev(s, "knows", "mirror", C("mettle", 30, "chorus", 60), false, 388f, 342.5f, Fx_(E(Fx.Power, "Sworn", 0.1), E(Fx.Rate, "dread", 0.1)), L("parted>=85"));
            r = Rev(s, "fear", "spiral", C("nacre", 50, "vellum", 40), false, 306f, 120.0f, Fx_(E(Fx.Speed, "sing", -1), E(Fx.Gain, "rally", -0.5), E(Fx.Rate, "dread", 3), E(Fx.Cap, "dread", 100)), L("vision:wake"));
            r.withdraws = L("shut");
            r.grants = L("ending:bad");
            r = Rev(s, "shut", "knot", C("lucidity", 80, "chorus", 60), false, 388f, 257.5f, Fx_(E(Fx.Power, "Sworn", 0.25), E(Fx.Gain, "rally", 1)), L("vision:wake"));
            r.withdraws = L("fear");
            r.grants = L("ending:good");
        }

        static VisionDef Vision(Dream s, string k, bool great, bool rep, float deg, List<Offer> of,
                                List<Effect> effects, List<string> requires)
        {
            var v = new VisionDef
            {
                k = k, n = T("vision." + k + ".name"), bl = T("vision." + k + ".text"),
                fx = Lines("vision." + k + ".fx"), of = of, sel = 0, p = 0f, rep = rep, done = 0,
                great = great, a = false, angle = deg * Mathf.Deg2Rad, effects = effects, requires = requires
            };
            s.visions.Add(v);
            return v;
        }

        static Offer O(string r, double n, double g) => new Offer { r = r, n = n, g = g };

        static void Visions(Dream s)
        {
            Vision(s, "door", true, false, 0.0f, new List<Offer> { O("hush", 10, 4), O("tallow", 10, 4), O("echo", 15, 4) }, Fx_(E(Fx.Rate, "dread", 0.2)), L("rev:camefrom"));
            Vision(s, "bell", false, false, 97.0f, new List<Offer> { O("echo", 20, 5), O("hush", 10, 5) }, Fx_(E(Fx.Gain, "conjure", 0.18)), L("rev:answers", "max:echo"));
            Vision(s, "vigil", false, false, 194.0f, new List<Offer> { O("tallow", 20, 5), O("ember", 10, 5) }, null, L("rev:answers"));
            Vision(s, "garden", false, false, 291.0f, new List<Offer> { O("hush", 20, 5), O("salt", 15, 5) }, null, L("rev:letsea"));
            Vision(s, "tide", false, true, 28.0f, new List<Offer> { O("salt", 20, 10), O("silt", 30, 10) }, Fx_(E(Fx.Gain, "sift", 0.1)), L("rev:tidefolk"));
            Vision(s, "unblink", false, true, 125.0f, new List<Offer> { O("echo", 30, 10), O("hush", 20, 10) }, Fx_(E(Fx.RevCost, null, 0.04)), L("rev:grew"));
            Vision(s, "well", false, false, 222.0f, new List<Offer> { O("nacre", 20, 10), O("echo", 40, 10) }, Fx_(E(Fx.Gain, "conjure", 0.4), E(Fx.Housing, "longhouse", 1)), L("rev:grew"));
            Vision(s, "hour", false, true, 319.0f, new List<Offer> { O("moonsilver", 60, 10), O("echo", 50, 10) }, Fx_(E(Fx.Speed, "*", 0.03)), L("rev:clocks"));
            Vision(s, "bridge", false, false, 56.0f, new List<Offer> { O("moonsilver", 80, 5), O("chorus", 15, 5) }, Fx_(E(Fx.Muster, null, 0.1)), L("rev:worry"));
            Vision(s, "tenant", true, false, 153.0f, new List<Offer> { O("echo", 60, 4), O("nacre", 20, 4), O("chorus", 20, 4) }, Fx_(E(Fx.Cap, "dread", 100)), L("rev:wants"));
            Vision(s, "looked", false, false, 250.0f, new List<Offer> { O("mettle", 5, 5), O("ember", 30, 5) }, null, L("built:forge"));
            Vision(s, "duck", false, false, 347.0f, new List<Offer> { O("mettle", 8, 5), O("chorus", 20, 5) }, null, L("vision:looked"));
            Vision(s, "aloud", false, false, 84.0f, new List<Offer> { O("mettle", 12, 5), O("vellum", 15, 5) }, null, L("vision:duck"));
            Vision(s, "waiting", false, false, 181.0f, new List<Offer> { O("mettle", 18, 5), O("salt", 60, 5) }, null, L("vision:aloud"));
            Vision(s, "stayed", false, false, 278.0f, new List<Offer> { O("mettle", 25, 5), O("chorus", 40, 5) }, null, L("vision:waiting"));
            Vision(s, "make", false, false, 15.0f, new List<Offer> { O("mettle", 35, 5), O("nacre", 40, 5) }, null, L("vision:stayed"));
            Vision(s, "wake", true, false, 112.0f, new List<Offer> { O("nacre", 40, 4), O("vellum", 30, 4), O("mettle", 30, 4) }, null, L("parted>=95"));
        }

        static void Veil(Dream s, int ord, string name, double need, List<Amount> spend, List<Amount> bring,
                         int cap, double seconds, string entry)
        {
            var lines = Lines(entry);
            var reveal = new List<double>();
            for (int i = 0; i < lines.Count; i++) reveal.Add(System.Math.Floor(need * i / System.Math.Max(1, lines.Count)));
            s.veils.Add(new VeilDef
            {
                n = T(name), ord = ord, sunk = 0, need = need, spend = spend, bring = bring, w = 0, cap = cap,
                baseSeconds = seconds, entry = lines, reveal = reveal
            });
        }

        static void Veils(Dream s)
        {
            Veil(s, 1, "veil.shallows.name", 20, C("reverie", 1), C("silt", 1), 3, 6.2, "veil.shallows.entry");
            Veil(s, 2, "veil.drift.name", 60, C("reverie", 1), C("silt", 1, "echo", 0.5), 3, 6.4, "veil.drift.entry");
            Veil(s, 3, "veil.drift.name", 32, C("reverie", 1), C("silt", 1, "echo", 0.5), 3, 6.6, "veil.3.entry");
            Veil(s, 4, "veil.drift.name", 37, C("reverie", 1), C("silt", 1, "echo", 0.5), 4, 6.8, "veil.4.entry");
            Veil(s, 5, "veil.drift.name", 41, C("reverie", 1), C("silt", 1, "echo", 0.5), 4, 7.0, "veil.5.entry");
            Veil(s, 6, "veil.drift.name", 46, C("reverie", 1), C("silt", 1, "echo", 0.5), 4, 7.2, "veil.6.entry");
            Veil(s, 7, "veil.siltshore.name", 50, C("reverie", 1), C("silt", 1), 4, 7.4, "veil.7.entry");
            Veil(s, 8, "veil.siltshore.name", 55, C("reverie", 1), C("silt", 1), 5, 7.6, "veil.8.entry");
            Veil(s, 9, "veil.siltshore.name", 60, C("reverie", 1), C("silt", 1), 5, 7.8, "veil.9.entry");
            Veil(s, 10, "veil.siltshore.name", 64, C("reverie", 1), C("silt", 1), 5, 8.0, "veil.10.entry");
            Veil(s, 11, "veil.siltshore.name", 69, C("reverie", 1), C("silt", 1), 5, 8.2, "veil.11.entry");
            Veil(s, 12, "veil.siltshore.name", 74, C("reverie", 1), C("silt", 1), 6, 8.4, "veil.12.entry");
            Veil(s, 13, "veil.siltshore.name", 80, C("reverie", 2), C("silt", 1), 6, 8.6, "veil.13.entry");
            Veil(s, 14, "veil.stillwater.name", 85, C("reverie", 2), C("silt", 1, "lucidity", 0.25), 6, 8.8, "veil.14.entry");
            Veil(s, 15, "veil.stillwater.name", 90, C("reverie", 2), C("silt", 1, "lucidity", 0.25), 6, 9.0, "veil.15.entry");
            Veil(s, 16, "veil.stillwater.name", 96, C("reverie", 2), C("silt", 1, "lucidity", 0.25), 7, 9.2, "veil.16.entry");
            Veil(s, 17, "veil.stillwater.name", 101, C("reverie", 2), C("silt", 1, "lucidity", 0.25), 7, 9.4, "veil.17.entry");
            Veil(s, 18, "veil.stillwater.name", 107, C("reverie", 2), C("silt", 1, "lucidity", 0.25), 7, 9.6, "veil.18.entry");
            Veil(s, 19, "veil.stillwater.name", 112, C("reverie", 2), C("silt", 1, "lucidity", 0.25), 7, 9.8, "veil.19.entry");
            Veil(s, 20, "veil.stillwater.name", 118, C("reverie", 2), C("silt", 1, "lucidity", 0.25), 8, 10.0, "veil.20.entry");
            Veil(s, 21, "veil.lamplithollows.name", 124, C("reverie", 2), C("silt", 1, "tallow", 0.75), 8, 10.2, "veil.21.entry");
            Veil(s, 22, "veil.lamplithollows.name", 130, C("reverie", 2), C("silt", 1, "tallow", 0.75), 8, 10.4, "veil.22.entry");
            Veil(s, 23, "veil.lamplithollows.name", 136, C("reverie", 2), C("silt", 1, "tallow", 0.75), 8, 10.6, "veil.23.entry");
            Veil(s, 24, "veil.lamplithollows.name", 142, C("reverie", 2), C("silt", 1, "tallow", 0.75), 9, 10.8, "veil.24.entry");
            Veil(s, 25, "veil.lamplithollows.name", 148, C("reverie", 3), C("silt", 1, "tallow", 0.75), 9, 11.0, "veil.25.entry");
            Veil(s, 26, "veil.lamplithollows.name", 154, C("reverie", 3), C("silt", 1, "tallow", 0.75), 9, 11.2, "veil.26.entry");
            Veil(s, 27, "veil.coldseam.name", 161, C("reverie", 3), C("silt", 1, "moonsilver", 0.75), 9, 11.4, "veil.27.entry");
            Veil(s, 28, "veil.coldseam.name", 167, C("reverie", 3), C("silt", 1, "moonsilver", 0.75), 10, 11.6, "veil.28.entry");
            Veil(s, 29, "veil.coldseam.name", 174, C("reverie", 3), C("silt", 1, "moonsilver", 0.75), 10, 11.8, "veil.29.entry");
            Veil(s, 30, "veil.coldseam.name", 180, C("reverie", 3), C("silt", 1, "moonsilver", 1), 10, 12.0, "veil.30.entry");
            Veil(s, 31, "veil.coldseam.name", 187, C("reverie", 3), C("silt", 2, "moonsilver", 1), 10, 12.2, "veil.31.entry");
            Veil(s, 32, "veil.unlitstair.name", 194, C("reverie", 3), C("silt", 2, "hush", 1), 11, 12.4, "veil.32.entry");
            Veil(s, 33, "veil.unlitstair.name", 201, C("reverie", 3), C("silt", 2, "hush", 1), 11, 12.6, "veil.33.entry");
            Veil(s, 34, "veil.unlitstair.name", 208, C("reverie", 3), C("silt", 2, "hush", 1), 11, 12.8, "veil.34.entry");
            Veil(s, 35, "veil.unlitstair.name", 215, C("reverie", 3), C("silt", 2, "hush", 1), 11, 13.0, "veil.35.entry");
            Veil(s, 36, "veil.unlitstair.name", 222, C("reverie", 3), C("silt", 2, "hush", 1), 12, 13.2, "veil.36.entry");
            Veil(s, 37, "veil.housewithonewindow.name", 230, C("reverie", 4), C("silt", 2, "ember", 1), 12, 13.4, "veil.37.entry");
            Veil(s, 38, "veil.housewithonewindow.name", 237, C("reverie", 4), C("silt", 2, "ember", 1), 12, 13.6, "veil.38.entry");
            Veil(s, 39, "veil.housewithonewindow.name", 244, C("reverie", 4), C("silt", 2, "ember", 1), 12, 13.8, "veil.39.entry");
            Veil(s, 40, "veil.housewithonewindow.name", 60, C("reverie", 4, "dread", 1), C("silt", 2, "ember", 1), 13, 14.0, "veil.40.entry");
            Veil(s, 41, "veil.undertow.name", 260, C("reverie", 4), C("silt", 2, "echo", 2), 13, 14.2, "veil.41.entry");
            Veil(s, 42, "veil.undertow.name", 267, C("reverie", 4), C("silt", 2, "echo", 2), 13, 14.4, "veil.42.entry");
            Veil(s, 43, "veil.undertow.name", 275, C("reverie", 4), C("silt", 2, "echo", 2), 13, 14.6, "veil.43.entry");
            Veil(s, 44, "veil.undertow.name", 283, C("reverie", 4), C("silt", 2, "echo", 2), 14, 14.8, "veil.44.entry");
            Veil(s, 45, "veil.undertow.name", 291, C("reverie", 4), C("silt", 2, "echo", 2), 14, 15.0, "veil.45.entry");
            Veil(s, 46, "veil.undertow.name", 299, C("reverie", 4), C("silt", 2, "echo", 2), 14, 15.2, "veil.46.entry");
            Veil(s, 47, "veil.saltflats.name", 307, C("reverie", 4), C("silt", 2, "salt", 2), 14, 15.4, "veil.47.entry");
            Veil(s, 48, "veil.saltflats.name", 316, C("reverie", 4), C("silt", 2, "salt", 2), 15, 15.6, "veil.48.entry");
            Veil(s, 49, "veil.saltflats.name", 324, C("reverie", 5), C("silt", 2, "salt", 2), 15, 15.8, "veil.49.entry");
            Veil(s, 50, "veil.saltflats.name", 332, C("reverie", 5), C("silt", 2, "salt", 2.5), 15, 16.0, "veil.50.entry");
            Veil(s, 51, "veil.saltflats.name", 341, C("reverie", 5), C("silt", 2, "salt", 2.5), 15, 16.2, "veil.51.entry");
            Veil(s, 52, "veil.pearlbeds.name", 350, C("reverie", 5), C("silt", 2, "nacre", 0.75), 16, 16.4, "veil.52.entry");
            Veil(s, 53, "veil.pearlbeds.name", 358, C("reverie", 5), C("silt", 2, "nacre", 0.75), 16, 16.6, "veil.53.entry");
            Veil(s, 54, "veil.pearlbeds.name", 367, C("reverie", 5), C("silt", 2, "nacre", 0.75), 16, 16.8, "veil.54.entry");
            Veil(s, 55, "veil.pearlbeds.name", 376, C("reverie", 5), C("silt", 2, "nacre", 0.75), 16, 17.0, "veil.55.entry");
            Veil(s, 56, "veil.pearlbeds.name", 385, C("reverie", 5), C("silt", 2, "nacre", 0.75), 17, 17.2, "veil.56.entry");
            Veil(s, 57, "veil.wrackline.name", 394, C("reverie", 5), C("silt", 2, "vellum", 0.5), 17, 17.4, "veil.57.entry");
            Veil(s, 58, "veil.wrackline.name", 403, C("reverie", 5), C("silt", 2, "vellum", 0.5), 17, 17.6, "veil.58.entry");
            Veil(s, 59, "veil.wrackline.name", 413, C("reverie", 5), C("silt", 2, "vellum", 0.5), 17, 17.8, "veil.59.entry");
            Veil(s, 60, "veil.wrackline.name", 60, C("reverie", 5, "chorus", 1), C("silt", 2, "vellum", 0.5), 18, 18.0, "veil.60.entry");
            Veil(s, 61, "veil.hollowwood.name", 431, C("reverie", 6), C("silt", 3, "ward", 0.5), 18, 18.2, "veil.61.entry");
            Veil(s, 62, "veil.hollowwood.name", 441, C("reverie", 6), C("silt", 3, "ward", 0.5), 18, 18.4, "veil.62.entry");
            Veil(s, 63, "veil.hollowwood.name", 451, C("reverie", 6), C("silt", 3, "ward", 0.5), 18, 18.6, "veil.63.entry");
            Veil(s, 64, "veil.hollowwood.name", 460, C("reverie", 6), C("silt", 3, "ward", 0.5), 19, 18.8, "veil.64.entry");
            Veil(s, 65, "veil.hollowwood.name", 470, C("reverie", 6), C("silt", 3, "ward", 0.5), 19, 19.0, "veil.65.entry");
            Veil(s, 66, "veil.hallofclocks.name", 480, C("reverie", 6), C("silt", 3, "moonsilver", 2.5), 19, 19.2, "veil.66.entry");
            Veil(s, 67, "veil.hallofclocks.name", 490, C("reverie", 6), C("silt", 3, "moonsilver", 2.5), 19, 19.4, "veil.67.entry");
            Veil(s, 68, "veil.hallofclocks.name", 500, C("reverie", 6), C("silt", 3, "moonsilver", 2.5), 20, 19.6, "veil.68.entry");
            Veil(s, 69, "veil.hallofclocks.name", 510, C("reverie", 6), C("silt", 3, "moonsilver", 2.5), 20, 19.8, "veil.69.entry");
            Veil(s, 70, "veil.hallofclocks.name", 520, C("reverie", 6), C("silt", 3, "moonsilver", 3), 20, 20.0, "veil.70.entry");
            Veil(s, 71, "veil.waitingrooms.name", 531, C("reverie", 6), C("silt", 3, "salt", 3), 20, 20.2, "veil.71.entry");
            Veil(s, 72, "veil.waitingrooms.name", 541, C("reverie", 6), C("silt", 3, "salt", 3), 21, 20.4, "veil.72.entry");
            Veil(s, 73, "veil.waitingrooms.name", 552, C("reverie", 7), C("silt", 3, "salt", 3), 21, 20.6, "veil.73.entry");
            Veil(s, 74, "veil.waitingrooms.name", 562, C("reverie", 7), C("silt", 3, "salt", 3), 21, 20.8, "veil.74.entry");
            Veil(s, 75, "veil.waitingrooms.name", 573, C("reverie", 7), C("silt", 3, "salt", 3), 21, 21.0, "veil.75.entry");
            Veil(s, 76, "veil.mirrorstair.name", 584, C("reverie", 7), C("silt", 3, "nacre", 1.5), 22, 21.2, "veil.76.entry");
            Veil(s, 77, "veil.mirrorstair.name", 595, C("reverie", 7), C("silt", 3, "nacre", 1.5), 22, 21.4, "veil.77.entry");
            Veil(s, 78, "veil.mirrorstair.name", 606, C("reverie", 7), C("silt", 3, "nacre", 1.5), 22, 21.6, "veil.78.entry");
            Veil(s, 79, "veil.mirrorstair.name", 617, C("reverie", 7), C("silt", 3, "nacre", 1.5), 22, 21.8, "veil.79.entry");
            Veil(s, 80, "veil.mirrorstair.name", 60, C("reverie", 7, "mettle", 1), C("silt", 3, "nacre", 1.5), 23, 22.0, "veil.80.entry");
            Veil(s, 81, "veil.gatheringshore.name", 639, C("reverie", 7), C("silt", 3, "chorus", 1.5), 23, 22.2, "veil.81.entry");
            Veil(s, 82, "veil.gatheringshore.name", 651, C("reverie", 7), C("silt", 3, "chorus", 1.5), 23, 22.4, "veil.82.entry");
            Veil(s, 83, "veil.gatheringshore.name", 662, C("reverie", 7), C("silt", 3, "chorus", 1.5), 23, 22.6, "veil.83.entry");
            Veil(s, 84, "veil.gatheringshore.name", 674, C("reverie", 7), C("silt", 3, "chorus", 1.5), 24, 22.8, "veil.84.entry");
            Veil(s, 85, "veil.gatheringshore.name", 685, C("reverie", 8), C("silt", 3, "chorus", 1.5), 24, 23.0, "veil.85.entry");
            Veil(s, 86, "veil.understair.name", 697, C("reverie", 8), C("echo", 6.5, "silt", 3), 24, 23.2, "veil.86.entry");
            Veil(s, 87, "veil.understair.name", 709, C("reverie", 8), C("echo", 6.5, "silt", 3), 24, 23.4, "veil.87.entry");
            Veil(s, 88, "veil.understair.name", 720, C("reverie", 8), C("echo", 6.5, "silt", 3), 25, 23.6, "veil.88.entry");
            Veil(s, 89, "veil.understair.name", 732, C("reverie", 8), C("echo", 6.5, "silt", 3), 25, 23.8, "veil.89.entry");
            Veil(s, 90, "veil.understair.name", 744, C("reverie", 8), C("echo", 6.5, "silt", 3), 25, 24.0, "veil.90.entry");
            Veil(s, 91, "veil.lastlamp.name", 757, C("reverie", 8), C("silt", 4, "tallow", 6.5, "ember", 3.5), 25, 24.2, "veil.91.entry");
            Veil(s, 92, "veil.lastlamp.name", 769, C("reverie", 8), C("silt", 4, "tallow", 6.5, "ember", 3.5), 26, 24.4, "veil.92.entry");
            Veil(s, 93, "veil.lastlamp.name", 781, C("reverie", 8), C("silt", 4, "tallow", 6.5, "ember", 3.5), 26, 24.6, "veil.93.entry");
            Veil(s, 94, "veil.lastlamp.name", 794, C("reverie", 8), C("silt", 4, "tallow", 6.5, "ember", 3.5), 26, 24.8, "veil.94.entry");
            Veil(s, 95, "veil.lastlamp.name", 806, C("reverie", 8), C("silt", 4, "tallow", 7, "ember", 3.5), 26, 25.0, "veil.95.entry");
            Veil(s, 96, "veil.lastlamp.name", 819, C("reverie", 8), C("silt", 4, "tallow", 7, "ember", 3.5), 27, 25.2, "veil.96.entry");
            Veil(s, 97, "veil.doorajar.name", 831, C("reverie", 9), C(), 27, 25.4, "veil.97.entry");
            Veil(s, 98, "veil.doorajar.name", 844, C("reverie", 9), C(), 27, 25.6, "veil.98.entry");
            Veil(s, 99, "veil.doorajar.name", 857, C("reverie", 9), C(), 27, 25.8, "veil.99.entry");
            Veil(s, 100, "veil.doorajar.name", 870, C("reverie", 9), C(), 28, 26.0, "veil.100.entry");
            Veil(s, 101, "veil.bottom.name", 999999, C("reverie", 9), C("silt", 4, "moonsilver", 2, "echo", 4), 30, 24, "veil.bottom.entry");
        }

        static RoadLocation Place(Dream s, string k, float t, double en, List<Effect> effects, List<string> grants,
                                  List<string> requires)
        {
            var l = new RoadLocation
            {
                k = k, n = T("place." + k + ".name"), t = t, won = false, en = en,
                bl = T("place." + k + ".blurb"), ben = T("place." + k + ".ben"),
                effects = effects, grants = grants, requires = requires
            };
            s.road.Add(l);
            return l;
        }

        static void Unit(Dream s, string k, string sec, double p, double growth, List<Amount> cost, List<string> requires)
        {
            s.units.Add(new UnitDef
            {
                k = k, n = T("unit." + k + ".name"), bl = T("unit." + k + ".blurb"), p = p, c = 0,
                sec = sec, growth = growth, cost = cost, requires = requires
            });
        }

        static void Road(Dream s)
        {
            Place(s, "gate", 0.03f, 3, null, null, L("parted>=58"));
            Place(s, "thunder", 0.062f, 5, Fx_(E(Fx.Gain, "*", 0.05)), null, L("parted>=58"));
            Place(s, "aisle", 0.095f, 8, Fx_(E(Fx.Power, "Levied", 0.25)), null, L("parted>=59"));
            Place(s, "ford", 0.127f, 14, null, null, L("parted>=61"));
            Place(s, "deepend", 0.16f, 22, null, null, L("parted>=63"));
            Place(s, "principal", 0.192f, 34, Fx_(E(Fx.Gain, "*", 0.05)), null, L("parted>=65"));
            Place(s, "orchard", 0.224f, 50, null, null, L("parted>=67"));
            Place(s, "bell", 0.257f, 80, null, null, L("parted>=70"));
            Place(s, "mile", 0.289f, 120, null, null, L("parted>=73"));
            Place(s, "ninth", 0.322f, 600, Fx_(E(Fx.Power, "Sworn", 0.25)), null, L("parted>=76"));
            Place(s, "playground", 0.354f, 1800, Fx_(E(Fx.Gain, "*", 0.1)), null, L("parted>=80"));
            Place(s, "exam", 0.387f, 2600, null, null, L("parted>=80"));
            Place(s, "stage", 0.419f, 3500, Fx_(E(Fx.Muster, null, 0.1)), null, L("parted>=80"));
            Place(s, "diary", 0.451f, 6000, Fx_(E(Fx.CapPct, "vellum", 1)), null, L("parted>=82"));
            Place(s, "phone", 0.484f, 9000, Fx_(E(Fx.Gain, "*", 0.1)), null, L("parted>=83"));
            Place(s, "waiting", 0.516f, 14000, Fx_(E(Fx.Housing, "longhouse", 1)), null, L("parted>=85"));
            Place(s, "interview", 0.549f, 19000, Fx_(E(Fx.Gain, "temper", 0.25)), null, L("parted>=86"));
            Place(s, "office", 0.581f, 28000, Fx_(E(Fx.Power, "Sworn", 0.25)), null, L("parted>=87"));
            Place(s, "rising", 0.613f, 36000, Fx_(E(Fx.Rate, "dread", -0.2)), null, L("parted>=88"));
            Place(s, "chair", 0.646f, 48000, Fx_(E(Fx.Gain, "rally", 0.25)), null, L("parted>=89"));
            Place(s, "faces", 0.678f, 120000, Fx_(E(Fx.CapPct, "chorus", 1)), null, L("parted>=91"));
            Place(s, "clock", 0.711f, 160000, Fx_(E(Fx.Speed, "*", 0.1)), null, L("parted>=93"));
            Place(s, "mirror", 0.743f, 200000, Fx_(E(Fx.Enemy, null, 0.1)), null, L("parted>=95"));
            Place(s, "stairtop", 0.776f, 260000, Fx_(E(Fx.Power, "Sworn", 0.25)), null, L("parted>=97"));
            Place(s, "landing", 0.808f, 370000, null, null, L("parted>=100", "chose"));
            Place(s, "hallway", 0.84f, 395000, null, null, L("parted>=100", "chose"));
            Place(s, "understair", 0.873f, 420000, null, null, L("parted>=100", "chose"));
            Place(s, "wardrobe", 0.905f, 445000, null, null, L("parted>=100", "chose"));
            Place(s, "underbed", 0.938f, 470000, null, null, L("parted>=100", "chose"));
            Place(s, "nobody", 0.97f, 490000, null, L("gameover"), L("parted>=100", "chose"));
            Unit(s, "drifter", "Levied", 1, 1.12, C("echo", 6, "silt", 2), L("rev:mine"));
            Unit(s, "guard", "Levied", 3, 1.12, C("echo", 10, "ward", 2), L("won:ford"));
            Unit(s, "bearer", "Levied", 8, 1.12, C("tallow", 8, "ward", 3), L("won:orchard"));
            Unit(s, "unflinching", "Sworn", 20, 1.06, C("mettle", 4, "ward", 4), L("vision:looked"));
            Unit(s, "laughing", "Sworn", 50, 1.06, C("mettle", 8, "chorus", 6), L("vision:duck"));
            Unit(s, "plainspoken", "Sworn", 120, 1.06, C("mettle", 15, "vellum", 8), L("vision:aloud"));
            Unit(s, "sentinel", "Sworn", 300, 1.06, C("mettle", 28, "salt", 30), L("vision:waiting"));
            Unit(s, "chorus", "Sworn", 700, 1.06, C("mettle", 50, "chorus", 30, "echo", 40), L("vision:stayed"));
            Unit(s, "dreamwright", "Sworn", 1800, 1.06, C("mettle", 90, "vellum", 40, "nacre", 30), L("vision:make"));
        }

        static void J(Dream s, string id, int d, int ch, string src, bool great, List<string> requires)
        {
            s.journalDefs.Add(new JournalEntry
            {
                id = id, d = d, ch = ch, src = src, great = great, n = T("journal." + id + ".name"), seen = false,
                requires = requires, p = Lines("journal." + id + ".p")
            });
        }

        static void Journal(Dream s)
        {
            J(s, "doorway", 1, 1, "veil", false, L("start"));
            J(s, "altar", 3, 1, "veil", false, L("built:altar"));
            J(s, "listening", 14, 1, "revelation", false, L("rev:listening"));
            J(s, "drift", 9, 1, "veil", false, L("parted:1"));
            J(s, "afraid", 80, 1, "revelation", true, L("rev:afraid"));
            J(s, "lamps", 92, 2, "revelation", false, L("rev:lamps"));
            J(s, "tasted", 150, 2, "revelation", false, L("rev:tasted"));
            J(s, "door", 160, 2, "vision", true, L("vision:door"));
            J(s, "lamp", 170, 3, "vision", false, L("vision:vigil"));
            J(s, "tide1", 190, 3, "vision", false, L("vdone:tide>=1"));
            J(s, "tide2", 196, 3, "vision", false, L("vdone:tide>=2"));
            J(s, "tide3", 202, 3, "vision", false, L("vdone:tide>=3"));
            J(s, "tide4", 208, 3, "vision", false, L("vdone:tide>=4"));
            J(s, "tide5", 214, 3, "vision", false, L("vdone:tide>=5"));
            J(s, "tide6", 220, 3, "vision", false, L("vdone:tide>=6"));
            J(s, "mine", 238, 3, "revelation", true, L("rev:mine"));
            J(s, "gate", 244, 4, "assault", false, L("won:gate"));
            J(s, "wants", 290, 4, "revelation", false, L("rev:wants"));
            J(s, "tenant", 300, 4, "vision", true, L("vision:tenant"));
            J(s, "made", 318, 4, "revelation", true, L("rev:made"));
            J(s, "everypeople", 336, 5, "revelation", false, L("rev:everypeople"));
            J(s, "knows", 350, 5, "revelation", false, L("rev:knows"));
            J(s, "wake", 380, 5, "vision", true, L("vision:wake"));
            J(s, "fear", 384, 5, "revelation", true, L("rev:fear"));
            J(s, "shut", 384, 5, "revelation", true, L("rev:shut"));
            J(s, "landing", 390, 5, "assault", false, L("won:landing"));
            J(s, "hallway", 394, 5, "assault", false, L("won:hallway"));
            J(s, "understair", 398, 5, "assault", false, L("won:understair"));
            J(s, "wardrobe", 402, 5, "assault", false, L("won:wardrobe"));
            J(s, "underbed", 406, 5, "assault", false, L("won:underbed"));
            J(s, "nobody", 410, 5, "assault", true, L("won:nobody"));
        }

        static void Ach(Dream s, string k, string group, string glyph, List<string> when)
        {
            s.achievements.Add(new AchievementDef
            {
                k = k, group = T("ach.group." + group), glyph = glyph,
                n = T("ach." + k + ".name"), hint = T("ach." + k + ".hint"), req = T("ach." + k + ".req"),
                when = when
            });
        }

        static void Achievements(Dream s)
        {
            Ach(s, "drift", "story", "drift", L("parted:1"));
            Ach(s, "arrival", "story", "drift", L("parted>=20"));
            Ach(s, "lamps", "story", "drift", L("parted>=40"));
            Ach(s, "tide", "story", "drift", L("parted>=60"));
            Ach(s, "road", "story", "drift", L("parted>=80"));
            Ach(s, "bottom", "story", "drift", L("parted>=100"));
            Ach(s, "good", "story", "drift", L("won:nobody", "ending:good"));
            Ach(s, "bad", "story", "drift", L("won:nobody", "ending:bad"));
        }
    }
}
